name: Playwright Automation Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  report:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./capday_1

    steps:
    - name: Checkout local code repository
      uses: actions/checkout@v4

    # 🔽 THIS IS THE EXACT SECTION YOU ARE UPDATING 🔽
    - name: Set up Node.js runtime environment
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: './capday_1/package-lock.json' 
    # 🔼 THIS IS THE EXACT SECTION YOU ARE UPDATING 🔼

    - name: Install project dependencies
      run: npm ci

    - name: Install Playwright Browsers system binaries
      run: npx playwright install --with-deps

    - name: Execute Playwright Automation Tests
      run: npx playwright test

    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./capday_1/allure-report